name: Test Build (in a Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 1 * *' # run at 2 AM UTC
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nuitka-nogil-testing:$(date +%s)
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: nuitka crash report
        path: |
          nuitka-crash-report.xml
