# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build on Runner (No Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python nogil-3.9.10
      run: |
        pyenv install nogil-3.9.10
        pyenv global nogil-3.9.10
        python -V
    - name: Install dependencies
      run: |
        pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
        pip install --no-cache-dir -r requirements.txt
    - name: Build Nuitka App
      run: |
        python -m nuitka main.py
