# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build on Runner (No Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - ' 3.13.0-rc.1'

    steps:
    - uses: actions/checkout@v4
    # - name: Set up Python nogil-3.9.10
    #   run: |
    #     curl https://pyenv.run | bash
    #     /home/runner/.pyenv/bin/pyenv install nogil-3.9.10
    #     /home/runner/.pyenv/bin/pyenv global nogil-3.9.10
    #     python -V
    - name: Install Python (with pyenv)
      uses: gabrielfalcao/pyenv-action@v18
      with:
        default: "${{ matrix.python }}"
        # command: pip install -U pip  # upgrade pip after installing python
    - name: Install dependencies
      run: |
        pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
        pip install --no-cache-dir -r requirements.txt
    - name: Build Nuitka App
      run: |
        python -m nuitka main.py
